import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/navbar";
import AuthProvider from "./Context/AuthContext";
import Routing from "./Context/routing";
import CartContext from "./Context/CartContext";

const inter = Montserrat({
  subsets: ["latin"],
  weight: ["200", "400", "500", "600"],
});

export const metadata = {
  title: "Moxtil-Cyber E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Routing>
          <CartContext>
            <AuthProvider>
              <Navbar />
              {children}
            </AuthProvider>
          </CartContext>
        </Routing>
      </body>
    </html>
  );
}
